language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG" == "dhis2/maintenance-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ];then 
     mvn clean deploy --settings deploy/settings.xml && exit 0; 
  fi
env:
  global:
  - secure: h0v3/UP6Iw1c2bMaMX6av7XiGg7AbBZdYnp8ntwxpVQA5fw0EXL61pUSgIeLOwIoM0JlO81sG7yJg6Tr0IzRzwmMaLWuSYb6Tn7CPeMp1xQ9BvXHkvQmaltoAJJocjBD4VRvNBHYauDW5M0tszJT/PQN2QaKS9DY7zzXTKGoKzPteDu50n8+P21rZJjXmYpkNE6Gf9eSp39CAtg6JSo+TIPwXjLOdnXZnrTY91Bjkz3ZpDOIR48c9bf/w0vkodF851532Nj3POVTGQFqdIMYPN0mW6Kr5kkizXVjFmOwJ9AS6mnkWpKCnAt446QQEtHxgVmJqGcI6x938ZjzIScbw0ZraKBsN55CglWwuFkpZT2PbJMr/R31gFOn8MhbmnSQduZAF+pjByRXf2M8Ev6cXMV08hisUerafROUHjDxUDr47hUyZATPUBk1wWxGlW5JT8AouYrQjer4xvbFSN/IQpzF9TA8CulxzyoJB94A4iqby6LPYocDOmIUU4Qsr55HHVuSpRhzzJS4IUToFKdlTULcRTST4IJdxIX3dtPKhR+P210JgOz7FTLJQCE5qg5A16SxHWTigjxYM/7eWaUvwBha/ddA41MYu+Hmkgx+WWCgO+UqH7E3JNt6cZjka2eWUoQMEpTwT3S9Ug3IS7MNxfJxTNBjG6dqAZ+R/3VDmU8=
  - secure: DhDb2RVi2TWJqdTkTmiwz1l/Qw+oVmbbk9eOTPf7vV+ZRCHEAOG4YsfkvPnf5gJDtaVWhVRjPmliEzGzxgP3zOaOFx1wb+CjI/NN5lQeQI+HYc+Wa0JVGJD93AFURkAjq5239b9oZxa7XaTZc9HKXaMMYGXElVdv3Gaf99FWPhRBS0sfw8XoJaHPOjxJgtS5OAtOoMexLanZLjJZtUePIsDCE3oqb9qXQRUlimH1eQOKsnOgzJ7U77CPnqCAxzMp0Qgf5s9Qm/PTpIkTEUrwuBRB6NHy9sZTqO55tJOyvfIVkmV7XP1Vql/DRzHKPE5LWQwdWAIPfPXEWRkvcCUWv3WDFNcmRcpCPUyepKqwffFzRLBFKFa7FtWIAGkzcJWd+qx8gXG/2jj/Au5c0PlsAbzYy9Us1z7DObZKtNkAX6gNwNNzEMKq3Dp4yqqO0XOnU98WlFgRXQEUlZVwSjkx2of7hf/s5QsU6/c3rk5M47IFKXcQ2XkMxFlSH9kcBp/N+K+ePQknrRSrlsBC+qxza1rL6j2DSxc9y2RWjkCnF13FrnfA6jnJRTrwckKEzU7/eQi83ELky4fL149iQrfaGjheyaU1llQp4vr+FaprNpf9k6v9TgN/SaOJLGWtOLntKO1pJ/pCFCuCqRtTvfcCNre8Szym8AFLjCRbu+2p9MA=
notifications:
  slack:
    secure: ebgMYULQtJ8znNboQgD46c0SFriyfMVFujDBrq9vOdJiMC2PEX3numNDHSCyfQz2L3/lsRhDQ1ex687pMh2m+wQR1937z1jvOANsLnBuhVRKAwFu3L9YSLqhzJ/Nyz+uE8g6QBdYBPoN7DvntClr0tiWXxj+Zg3e2lN2PLrRvnp9Opp9h71b43fXbMPDqISoU8q/EmkzLnGoO6u7t3QgE7FQezdq9JUrTL+5UKQwyv7C3psEr1ytXGpyMxT0K2aikbyF8TF/2hIlrD8ibQt6iuuf7CSpzUq8VGVUffBJLOPiu8N0/GgAq/39UvOgq/Ic+uPoXmFLg2lfCnGaKoYhye4J0iiMdkU04UdQdnqcvoEFgHsVYgT2exUtdOLzxxkmq7NgHrBq3hpKC9ay6ENUsBVo4rj2Lev9KQPLZIILzX8rFAqfG1jsVi89R8yaepMvWQeqAI0VHPHpm7uyf5BjP9dEHIH/ms3+voptx6wbQ5KfU4LqcOeMKj+EAD3vCsxcE6DkC6lwx/9BwGTjShcByc60c519qc1Ft56fDU28W1szYPAurPzmLsPDenT5xTcr7Xmv6v7HMslblHH4n7bQpHoi9haJlKGbvZXOqsUK4fFI35+vTsjams8oyYMTwpF4cXnb6EmPPO9742xgSFtmbaqxMgAEAuTsHNEbyyRmZ+U=
    on_success: change
    on_failure: always
